import React from "react";
import { FaShieldAlt, FaSearch, FaDesktop, FaNetworkWired, FaRobot } from "react-icons/fa";
import { MdSecurity, MdOutlineSecurityUpdateGood } from "react-icons/md";
import { IoIosAlert } from "react-icons/io";
import AnimatedTitle from "./AnimatedTitle";

const SecurityCard = ({ icon, title, description }) => {
  return (
    <div className="flex flex-col items-start p-6 transition-all duration-300 hover:bg-black/5 rounded-lg border border-transparent hover:border-gray-200">
      <div className="mb-4 p-3 bg-blue-600 text-white rounded-full">
        {icon}
      </div>
      <h3 className="text-xl font-bold mb-2">{title}</h3>
      <p className="text-gray-600 text-sm">{description}</p>
    </div>
  );
};

const SecurityServices = () => {
  const securityServices = [
    {
      icon: <FaSearch size={24} />,
      title: "SIEM Solutions",
      description: "Our Security Information and Event Management solutions provide real-time analysis of security alerts generated by applications and network hardware. Advanced correlation, AI analysis, and comprehensive dashboards ensure total visibility."
    },
    {
      icon: <MdSecurity size={24} />,
      title: "XDR Platform",
      description: "Extended Detection and Response solutions that unify security telemetry across endpoints, networks, cloud workloads, and applications. Get integrated threat protection with automated incident response capabilities."
    },
    {
      icon: <FaDesktop size={24} />,
      title: "EDR Protection",
      description: "Endpoint Detection and Response systems monitor endpoint and network events and record the information in a central database for analysis, detection, investigation, reporting, and alerting."
    },
    {
      icon: <FaRobot size={24} />,
      title: "SOAR Integration",
      description: "Security Orchestration, Automation and Response platforms that coordinate automated responses to security events, streamlining workflows and integrating with your existing security infrastructure."
    },
    {
      icon: <IoIosAlert size={24} />,
      title: "Threat Intelligence",
      description: "Proactive threat hunting and intelligence services to identify emerging threats before they impact your organization, with actionable insights from global threat landscapes."
    },
    {
      icon: <MdOutlineSecurityUpdateGood size={24} />,
      title: "Managed Security",
      description: "24/7 security monitoring and management services from our expert team, ensuring continuous protection and rapid response to security incidents."
    },
    {
      icon: <FaNetworkWired size={24} />,
      title: "Network Security",
      description: "Comprehensive network protection including firewalls, intrusion detection/prevention, secure access solutions, and network monitoring to safeguard your critical infrastructure."
    },
    {
      icon: <FaShieldAlt size={24} />,
      title: "Cloud Security",
      description: "Specialized protection for cloud environments, ensuring data security, compliance, and threat protection across multi-cloud and hybrid deployments."
    }
  ];

  return (
    <section id="security-services" className="py-20 bg-gradient-to-b from-white to-blue-50">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <p className="font-general text-sm uppercase md:text-[10px] mb-2">
            security.techanv.com
          </p>
          
          <AnimatedTitle
            title="Comprehe<b>n</b>sive Cybersecurity <br /> Solutio<b>n</b>s"
            containerClass="mt-5 !text-black text-center"
          />
          
          <p className="max-w-2xl mx-auto mt-6 text-gray-600">
            TECHANV provides enterprise-grade security solutions to protect your organization's 
            most valuable assets. Our integrated security platform combines cutting-edge 
            technologies with expert management.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {securityServices.map((service, index) => (
            <SecurityCard
              key={index}
              icon={service.icon}
              title={service.title}
              description={service.description}
            />
          ))}
        </div>

        <div className="mt-16 text-center">
          <div className="inline-block bg-blue-600 text-white rounded-lg px-6 py-3 text-lg font-semibold transition-all hover:bg-blue-700 cursor-pointer">
            Explore Our Solutions
          </div>
          <p className="mt-4 text-gray-500">
            Contact us at <span className="font-medium">security@techanv.com</span> for a personalized security assessment
          </p>
        </div>
      </div>

      <div className="container mx-auto mt-32 px-4">
        <div className="bg-blue-900 text-white rounded-2xl p-10 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-1/2 h-full opacity-10">
            <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
              <path fill="#FFFFFF" d="M40.8,-68.3C51.4,-61.2,57.9,-47.3,64.2,-33.3C70.6,-19.3,76.8,-5.2,75.7,8.3C74.6,21.8,66.2,34.9,55.9,45.3C45.6,55.8,33.3,63.7,19.6,68.7C5.8,73.8,-9.5,76,-23.1,72.2C-36.7,68.3,-48.7,58.5,-56.9,46C-65.2,33.5,-69.7,18.3,-70.3,3.1C-70.9,-12.1,-67.7,-27.2,-59.7,-38.2C-51.6,-49.1,-38.8,-55.9,-26.3,-61.7C-13.9,-67.5,-1.8,-72.3,10.8,-72.4C23.4,-72.6,30.1,-75.5,40.8,-68.3Z" transform="translate(100 100)" />
            </svg>
          </div>
          
          <div className="relative z-10 max-w-2xl">
            <h2 className="text-3xl font-bold mb-6">Full-Spectrum Security Protection</h2>
            <p className="mb-8">
              The TECHANV security platform integrates SIEM, XDR, EDR, and SOAR capabilities
              to provide comprehensive defense against modern cyber threats. Our solution
              creates a security ecosystem that provides:
            </p>
            
            <ul className="space-y-4">
              <li className="flex items-start gap-3">
                <div className="mt-1 bg-blue-500 p-1 rounded-full">
                  <FaShieldAlt />
                </div>
                <span>Real-time threat detection across all network endpoints and cloud resources</span>
              </li>
              <li className="flex items-start gap-3">
                <div className="mt-1 bg-blue-500 p-1 rounded-full">
                  <FaShieldAlt />
                </div>
                <span>Automated incident response for immediate threat containment</span>
              </li>
              <li className="flex items-start gap-3">
                <div className="mt-1 bg-blue-500 p-1 rounded-full">
                  <FaShieldAlt />
                </div>
                <span>Continuous security monitoring with 24/7 expert oversight</span>
              </li>
              <li className="flex items-start gap-3">
                <div className="mt-1 bg-blue-500 p-1 rounded-full">
                  <FaShieldAlt />
                </div>
                <span>Advanced security analytics and threat intelligence</span>
              </li>
            </ul>
            
            <div className="mt-10 inline-block bg-white text-blue-900 rounded-lg px-6 py-3 font-semibold transition-all hover:bg-blue-100 cursor-pointer">
              Schedule a Demo
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default SecurityServices;